# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
