# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurdOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_id', models.IntegerField()),
                ('prod_cost', models.IntegerField()),
                ('prod_color', models.CharField(max_length=100)),
                ('prod_weight', models.IntegerField()),
            ],
        ),
    ]
